name = "workers-airtable-form"
type = "javascript"

account_id = "8de699bb79e6fabd5d3d26e1db8a1190"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appeSWNykwi3SMV4O"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "https://workers-airtable-form.wrio.workers.dev"
